### ISSUE TITLE
Multiplatform API library

### ISSUE THREAD

**Issue by davidoskky** [aminecmi/ReaderForSelfoss-multiplatform#31]
The retrofit library used for communicating with the Rest API has the same problem as Room and Dagger: it's based on Java code and thus it cannot be used in shared code for iOS.
Using a kotlin library would simplify the application since we would only need to write the code once and then it could work for both Android and iOS.

[ktor](https://ktor.io/docs/getting-started-ktor-client-multiplatform-mobile.html) appears to be an established library with KMM support.

**Comment by aminecmi** [comment]
Ktor is already setup, and is used.
